### PR TITLE
some edits and additions to JM notes

### PR DESCRIPTION
**Pull request by higgi13425**
Saw your great notes, thought I might learn how to fork/clone/edit/push/pull request with this example. I just edited the .md file. 
Curious to see if this works.

### CODE REVIEW

**Review by jminnier — APPROVED** [review]
awesome!! this is fun experimenting! thanks for the super excellent contributions 👏

**Comment by jminnier** [comment]
Now you can experiment with updating your forked repo with my changes (add remote upstream?)! We're learning so much!

**Comment by higgi13425** [comment]
made some progress, in terminal, did
**_git remote -v_**
then copied URL of your repo from github
then 
_**git remote add upstream https://github.com/jminnier/rstudioconf18_jennybryan_forgot.git**_

then
**_git-remote -v_**
to confirm

Now linked, but not sure how to sync at this point. Pull seems to pull from my forked repo.

**Comment by jminnier** [comment]
nice! I've only done this a couple times but used this: https://help.github.com/articles/syncing-a-fork/
there might be a better way in Rstudio

**Comment by higgi13425** [comment]
Day 2 text now appears!!

**Comment by higgi13425** [comment]
To recap syncing a fork
In Terminal tab in Rstudio:
**_git fetch upstream
git checkout master
git merge upstream/master_**

**Pull request merged**
